version: '3'

services: 
  app:
    build:
      context: node
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://db:3306 node index.js
    image: miguelviannafeiteira/app
    container_name: app
    ports: 
      - "3000:3000"
    depends_on:
      - db
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - "./mysql:/var/lib/mysql"
    environment: 
      - MYSQL_DATABASE=nodedb 
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network 

  nginx:
    build:
        context: nginx
        dockerfile: Dockerfile
    # entrypoint: dockerize -wait 0.0.0.0:3000->3000/tcp docker-entrypoint.sh
    image: nginx
    container_name: nginx
    ports:
        - "8080:80"
    networks: 
        - node-network 
    depends_on:
        - db
        - app

networks:
  node-network:
    driver: bridge