version: '3'

services: 
  app:
    build:
      context: node
      dockerfile: Dockerfile
    image: miguelviannafeiteira/hello-express
    container_name: app
    ports: 
      - "3000:3000"
    depends_on:
      - db
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - "./mysql:/var/lib/mysql"
    environment: 
      - MYSQL_DATABASE=nodedb 
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network 

networks:
  node-network:
    driver: bridge